version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
            - run: yarn deploy
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test

workflows:
    test:
      jobs:
        - build-and-test
          filters:
              branches:
                ignore:
                  - master
    build-and-deploy:
      jobs:
       - build-and-deploy
        filters:
             branches:
               only:
                 - master