version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          with-cache: true
      - run: cd shop
      - run: yarn deploy

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
