version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
      - node/install-packages:
          pkg-manager: yarn
          with-cache: true
      - run: yarn deploy

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
